---
name: "CI"

on:
  push:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} (${{ matrix.tox-envs }})"
    runs-on: "ubuntu-latest"
    env:
      PY_COLORS: 1

    strategy:
      matrix:
        include:
          - python-version: "2.7"
            tox-envs: "py27"
            continue-on-error: false
          - python-version: "3.7"
            tox-envs: "py37"
            continue-on-error: false
          - python-version: "3.8"
            tox-envs: "py38"
            continue-on-error: false
          - python-version: "3.9"
            tox-envs: "py39"
            continue-on-error: false
          - python-version: "3.10"
            tox-envs: "py310"
            continue-on-error: false
          - python-version: "2.7"
            tox-envs: "py27-ansible19,py27-ansible24,py27-ansible25,py27-ansible26,py27-ansible27,py27-ansible28,py27-ansible29,py27-ansible210"
            continue-on-error: false
          - python-version: "3.7"
            tox-envs: "py37-ansible25,py37-ansible26,py37-ansible27,py37-ansible28,py37-ansible29,py37-ansible210"
            continue-on-error: false
          - python-version: "3.8"
            tox-envs: "py38-ansible25,py38-ansible26,py38-ansible27,py38-ansible28,py38-ansible29,py38-ansible210"
            continue-on-error: false
          - python-version: "3.9"
            tox-envs: "py39-ansible25,py39-ansible26,py39-ansible27,py39-ansible28,py39-ansible29,py39-ansible210"
            continue-on-error: false
          - python-version: "3.10"
            tox-envs: "py310-ansiblecore211,py310-ansiblecore212,py310-ansiblecore213"
            continue-on-error: false

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox

      - name: "Run tox targets for ${{ matrix.python-version }}"
        continue-on-error: "${{ matrix.continue-on-error }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes
